export default {
  THEME_CHANGE: 'THEME_CHANGE',
  THEME_INIT: 'THEME_INIT',
  POPULAR_REFRESH: 'POPULAR_REFRESH', // 最热模块下拉刷新
  LOAD_POPULAR_FAIL: 'LOAD_POPULAR_FAIL', // 最热模块下拉刷新失败
  LOAD_POPULAR_SUCCESS: 'LOAD_POPULAR_SUCCESS', // 最热模块下拉刷新成功
}